<b><center><blockquote style="background-color:pink">Algorithme de regroupement en grappes

<blockquote style="background-color:SkyBlue">Préparation du fichier

In [1]:
import pandas as pa
import pylab as pl
import numpy as np

In [2]:
T1=pa.read_csv('ozo.csv',sep=",",header=0)
T1.head()

JOUR  O3obs  MOCAGE  TEMPE    RMH2O    NO2     NO STATION  VentMOD  VentANG
0     1     91    93.2   21.5  0.00847  1.602  0.424     Aix   9.5000 -0.64350
1     1    100   104.6   20.2  0.00881  2.121  0.531     Aix   8.0100 -0.04996
2     0     82   103.6   17.4  0.00951  1.657  0.467     Aix   9.3771 -0.12832
3     0     94    94.8   18.8  0.00855  2.350  0.701     Aix   9.4578 -0.34516
4     0    107    99.0   23.7  0.00731  1.653  0.452     Aix   7.8791 -0.41822

In [3]:
T1["DepSeuil"]=T1["O3obs"].map(lambda x: x > 150)
T1.head()

JOUR  O3obs  MOCAGE  TEMPE    RMH2O    NO2     NO STATION  VentMOD  \
0     1     91    93.2   21.5  0.00847  1.602  0.424     Aix   9.5000   
1     1    100   104.6   20.2  0.00881  2.121  0.531     Aix   8.0100   
2     0     82   103.6   17.4  0.00951  1.657  0.467     Aix   9.3771   
3     0     94    94.8   18.8  0.00855  2.350  0.701     Aix   9.4578   
4     0    107    99.0   23.7  0.00731  1.653  0.452     Aix   7.8791   

   VentANG  DepSeuil  
0 -0.64350     False  
1 -0.04996     False  
2 -0.12832     False  
3 -0.34516     False  
4 -0.41822     False

In [4]:
T2=pa.concat([T1["TEMPE"],T1["RMH2O"],T1["NO2"],T1["NO"],T1["VentMOD"],T1["VentANG"]],axis=1)
T2.head()

TEMPE    RMH2O    NO2     NO  VentMOD  VentANG
0   21.5  0.00847  1.602  0.424   9.5000 -0.64350
1   20.2  0.00881  2.121  0.531   8.0100 -0.04996
2   17.4  0.00951  1.657  0.467   9.3771 -0.12832
3   18.8  0.00855  2.350  0.701   9.4578 -0.34516
4   23.7  0.00731  1.653  0.452   7.8791 -0.41822

In [5]:
std=T2.std()
Moy=T2.mean()

In [6]:
T3=(T2-Moy)/std
T3.head()

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG
0 -0.456809 -0.477180 -0.470566 -0.276502  1.176311 -1.138817
1 -0.705972 -0.386063 -0.342206 -0.149751  0.688475 -0.300825
2 -1.242631 -0.198468 -0.456964 -0.225564  1.136073 -0.411458
3 -0.974302 -0.455740 -0.285569  0.051628  1.162494 -0.717604
4 -0.035148 -0.788050 -0.457953 -0.243333  0.645618 -0.820754

In [7]:
T3["DepSeuil"]=T1["DepSeuil"]
T3.head()

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG  DepSeuil
0 -0.456809 -0.477180 -0.470566 -0.276502  1.176311 -1.138817     False
1 -0.705972 -0.386063 -0.342206 -0.149751  0.688475 -0.300825     False
2 -1.242631 -0.198468 -0.456964 -0.225564  1.136073 -0.411458     False
3 -0.974302 -0.455740 -0.285569  0.051628  1.162494 -0.717604     False
4 -0.035148 -0.788050 -0.457953 -0.243333  0.645618 -0.820754     False

In [20]:
L=T3.columns[:-2]
L

Index(['TEMPE', 'RMH2O', 'NO2', 'NO', 'VentMOD', 'VentANG'], dtype='object')

In [21]:
def distance(i,j):
    return (sum ([(T3.at[i,a]-T3.at[j,a])**2 for a in L]))**0.5

<blockquote style="background-color:SkyBlue"> choix des premiers centroides(0) au hasard

In [22]:
from random import *

In [23]:
#si on veut 5 grappes
def choix_des_lignes(tableau):
    N=[]
    for i in range (5):
        N.append(randint(0,len(tableau)))
    return N

In [24]:
#premier regroupement en grappes
def cluster(tableau):
    C=[]
    N=choix_des_lignes(tableau)
    for i in range(len(tableau)):
        d=[]
        for j in range(5):
            d.append((distance(i,N[j]),j))
        m=min(d)
        C.append(m[1])
    return C  

In [25]:
N=choix_des_lignes(T3)

In [26]:
T3["cluster"]=cluster(T3)
T3.head()

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG  DepSeuil  \
0 -0.456809 -0.477180 -0.470566 -0.276502  1.176311 -1.138817     False   
1 -0.705972 -0.386063 -0.342206 -0.149751  0.688475 -0.300825     False   
2 -1.242631 -0.198468 -0.456964 -0.225564  1.136073 -0.411458     False   
3 -0.974302 -0.455740 -0.285569  0.051628  1.162494 -0.717604     False   
4 -0.035148 -0.788050 -0.457953 -0.243333  0.645618 -0.820754     False   

   cluster  
0        4  
1        4  
2        1  
3        4  
4        4

<blockquote style="background-color:SkyBlue">Variance du nuage avec ces 5 centroides(0)

In [27]:
def Var(i):
    S=0
    for j in range(len(T3)):
        if T3.at[j,"cluster"]==i:
            S=S+distance(j,N[i])
    return S
def Variance(tableau):
    V=0
    for i in range(5):
        V=V+Var(i)
    return V

In [28]:
Variance(T3)

2758.1285777793846

<blockquote style="background-color:SkyBlue">Deuxième étape : Position par le calcul des centroides(1)

In [29]:
TC0=T3.query("cluster==0")
moy0=TC0.mean()
TC1=T3.query("cluster==1")
moy1=TC1.mean()
TC2=T3.query("cluster==2")
moy2=TC2.mean()
TC3=T3.query("cluster==3")
moy3=TC3.mean()
TC4=T3.query("cluster==4")
moy4=TC4.mean()

In [30]:
import numpy as np
C=np.array([[moy0[i]for i in range(6)],[moy1[i]for i in range(6)],[moy2[i]for i in range(6)],[moy3[i]for i in range(6)],[moy4[i]for i in range(6)]])
C

array([[ 0.6684338 ,  0.09161239,  0.21545685,  0.09693264, -0.10882481,
         0.77546025],
       [-1.42850933,  0.05268541, -0.16564599,  0.14252767,  0.35181413,
         0.72476848],
       [-0.10414669, -0.97668944, -0.40519655, -0.28192689,  2.152745  ,
        -1.09336307],
       [-0.47582944, -0.06924205,  0.05569846,  0.08309865, -0.7165131 ,
        -0.19332531],
       [ 0.32819104,  0.56438733, -0.2687286 , -0.2710001 ,  0.5215596 ,
        -0.66634851]])

In [31]:
N1=pa.DataFrame(C,index=range(5),columns=L)
N1

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG
0  0.668434  0.091612  0.215457  0.096933 -0.108825  0.775460
1 -1.428509  0.052685 -0.165646  0.142528  0.351814  0.724768
2 -0.104147 -0.976689 -0.405197 -0.281927  2.152745 -1.093363
3 -0.475829 -0.069242  0.055698  0.083099 -0.716513 -0.193325
4  0.328191  0.564387 -0.268729 -0.271000  0.521560 -0.666349

<blockquote style="background-color:SkyBlue">On réaffecte les données par rapport aux centroides(1)

In [32]:
#Pour chaque élément, on calcule la distance aux différents centroides
def discentroide(i,j):
    return (sum ([(T3.at[i,a]-N1.at[j,a])**2 for a in L]))**0.5

In [33]:
def cluster1(tableau):
    C1=[]
    for i in range(len(tableau)):
        d=[]
        for j in range(5):
            d.append((discentroide(i,j),j))
        m=min(d)
        C1.append(m[1])
    return C1

In [34]:
T3["cluster1"]=cluster1(T3)
T3.head()

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG  DepSeuil  \
0 -0.456809 -0.477180 -0.470566 -0.276502  1.176311 -1.138817     False   
1 -0.705972 -0.386063 -0.342206 -0.149751  0.688475 -0.300825     False   
2 -1.242631 -0.198468 -0.456964 -0.225564  1.136073 -0.411458     False   
3 -0.974302 -0.455740 -0.285569  0.051628  1.162494 -0.717604     False   
4 -0.035148 -0.788050 -0.457953 -0.243333  0.645618 -0.820754     False   

   cluster  cluster1  
0        4         2  
1        4         1  
2        1         1  
3        4         2  
4        4         4

<blockquote style="background-color:SkyBlue">Calcul de la variance par rapport aux centroides(1)

In [35]:
def Var1(j):
    S=0
    for i in range(len(T3)):
        if T3.at[i,"cluster1"]==j:
            S=S+discentroide(i,j)
    return S
def Variance1(tableau):
    V=0
    for j in range(5):
        V=V+Var1(j)
    return V

In [36]:
Variance1(T3)

1807.9348402577016

<blockquote style="background-color:SkyBlue">Troisième étape : Calcul des centroides(2)

In [37]:
TC01=T3.query("cluster1==0")
moy01=TC01.mean()
TC11=T3.query("cluster1==1")
moy11=TC11.mean()
TC21=T3.query("cluster1==2")
moy21=TC21.mean()
TC31=T3.query("cluster1==3")
moy31=TC31.mean()
TC41=T3.query("cluster1==4")
moy41=TC41.mean()

In [38]:
C1=np.array([[moy01[i]for i in range(6)],[moy11[i]for i in range(6)],[moy21[i]for i in range(6)],[moy31[i]for i in range(6)],[moy41[i]for i in range(6)]])
C1

array([[ 0.75443891,  0.22267538,  0.47639838,  0.27694173, -0.26824966,
         0.77904862],
       [-1.28096415, -0.25486748, -0.27880417, -0.02896837, -0.01049753,
         0.78676579],
       [-0.13038993, -0.94950477, -0.41478371, -0.30487681,  1.8519956 ,
        -1.06411232],
       [-0.59738741, -0.18569124, -0.00732105,  0.07090287, -0.71957136,
        -0.31577365],
       [ 0.46288107,  0.67768404, -0.33588332, -0.34295472,  0.16683165,
        -0.74592661]])

In [39]:
N2=pa.DataFrame(C1,index=range(5),columns=L)
N2

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG
0  0.754439  0.222675  0.476398  0.276942 -0.268250  0.779049
1 -1.280964 -0.254867 -0.278804 -0.028968 -0.010498  0.786766
2 -0.130390 -0.949505 -0.414784 -0.304877  1.851996 -1.064112
3 -0.597387 -0.185691 -0.007321  0.070903 -0.719571 -0.315774
4  0.462881  0.677684 -0.335883 -0.342955  0.166832 -0.745927

<blockquote style="background-color:SkyBlue">On réaffecte les données par rapport aux centroides(2)

In [40]:
#Pour chaque élément, on calcule la distance aux différents centroides
def discentroide2(i,j):
    return (sum ([(T3.at[i,a]-N2.at[j,a])**2 for a in L]))**0.5

In [41]:
def cluster2(tableau):
    C2=[]
    for i in range(len(tableau)):
        d=[]
        for j in range(5):
            d.append((discentroide2(i,j),j))
        m=min(d)
        C2.append(m[1])
    return C2

In [42]:
T3["cluster2"]=cluster2(T3)
T3.head()

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG  DepSeuil  \
0 -0.456809 -0.477180 -0.470566 -0.276502  1.176311 -1.138817     False   
1 -0.705972 -0.386063 -0.342206 -0.149751  0.688475 -0.300825     False   
2 -1.242631 -0.198468 -0.456964 -0.225564  1.136073 -0.411458     False   
3 -0.974302 -0.455740 -0.285569  0.051628  1.162494 -0.717604     False   
4 -0.035148 -0.788050 -0.457953 -0.243333  0.645618 -0.820754     False   

   cluster  cluster1  cluster2  
0        4         2         2  
1        4         1         1  
2        1         1         2  
3        4         2         2  
4        4         4         2

<blockquote style="background-color:SkyBlue">Calcul de la variance par rapport aux centroides(2)

In [43]:
def Var2(j):
    S=0
    for i in range(len(T3)):
        if T3.at[i,"cluster2"]==j:
            S=S+discentroide2(i,j)
    return S
def Variance2(tableau):
    V=0
    for j in range(5):
        V=V+Var2(j)
    return V

In [44]:
Variance2(T3)

1757.7855200847432

In [45]:
(a0,b0)=(len(T3.query('DepSeuil==False and cluster2==0')),len(T3.query('DepSeuil==True and cluster2==0')))
(a0,b0)

(199, 102)

In [46]:
(a1,b1)=(len(T3.query('DepSeuil==False and cluster2==1')),len(T3.query('DepSeuil==True and cluster2==1')))
(a1,b1)

(183, 2)

<blockquote style="background-color:SkyBlue">Deuxième étape : Position par le calcul des centroides(3)


In [48]:
TC02=T3.query("cluster2==0")
moy02=TC02.mean()
TC12=T3.query("cluster2==1")
moy12=TC12.mean()
TC22=T3.query("cluster2==2")
moy22=TC22.mean()
TC32=T3.query("cluster2==3")
moy32=TC32.mean()
TC42=T3.query("cluster2==4")
moy42=TC42.mean()

In [51]:
C2=np.array([[moy02[i]for i in range(6)],[moy12[i]for i in range(6)],[moy22[i]for i in range(6)],[moy32[i]for i in range(6)],[moy42[i]for i in range(6)]])
C2

array([[ 0.75245804,  0.28991762,  0.73009191,  0.51061202, -0.28867511,
         0.76085111],
       [-1.02061181, -0.25639799, -0.3836987 , -0.2140132 , -0.17622252,
         0.84552887],
       [-0.10287756, -0.92860086, -0.41146798, -0.29984098,  1.71813914,
        -1.03446361],
       [-0.63054589, -0.28418567, -0.08924095,  0.01368576, -0.68070563,
        -0.43892742],
       [ 0.50625689,  0.75108093, -0.33950832, -0.35182598,  0.00985249,
        -0.69958253]])

In [52]:
N3=pa.DataFrame(C2,index=range(5),columns=L)
N3

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG
0  0.752458  0.289918  0.730092  0.510612 -0.288675  0.760851
1 -1.020612 -0.256398 -0.383699 -0.214013 -0.176223  0.845529
2 -0.102878 -0.928601 -0.411468 -0.299841  1.718139 -1.034464
3 -0.630546 -0.284186 -0.089241  0.013686 -0.680706 -0.438927
4  0.506257  0.751081 -0.339508 -0.351826  0.009852 -0.699583

<blockquote style="background-color:SkyBlue">On réaffecte les données par rapport aux centroides(3)

In [53]:
#Pour chaque élément, on calcule la distance aux différents centroides
def discentroide3(i,j):
    return (sum ([(T3.at[i,a]-N3.at[j,a])**2 for a in L]))**0.5

In [54]:
def cluster3(tableau):
    C3=[]
    for i in range(len(tableau)):
        d=[]
        for j in range(5):
            d.append((discentroide3(i,j),j))
        m=min(d)
        C3.append(m[1])
    return C3

In [55]:
T3["cluster3"]=cluster3(T3)
T3.head()

TEMPE     RMH2O       NO2        NO   VentMOD   VentANG  DepSeuil  \
0 -0.456809 -0.477180 -0.470566 -0.276502  1.176311 -1.138817     False   
1 -0.705972 -0.386063 -0.342206 -0.149751  0.688475 -0.300825     False   
2 -1.242631 -0.198468 -0.456964 -0.225564  1.136073 -0.411458     False   
3 -0.974302 -0.455740 -0.285569  0.051628  1.162494 -0.717604     False   
4 -0.035148 -0.788050 -0.457953 -0.243333  0.645618 -0.820754     False   

   cluster  cluster1  cluster2  cluster3  
0        4         2         2         2  
1        4         1         1         3  
2        1         1         2         2  
3        4         2         2         2  
4        4         4         2         2

<blockquote style="background-color:SkyBlue">Calcul de la variance par rapport aux centroides(3)

In [57]:
def Var3(j):
    S=0
    for i in range(len(T3)):
        if T3.at[i,"cluster3"]==j:
            S=S+discentroide3(i,j)
    return S
def Variance3(tableau):
    V=0
    for j in range(5):
        V=V+Var3(j)
    return V

In [58]:
Variance3(T3)

1730.4484155245225

In [60]:
pa.crosstab(T3['DepSeuil'],T3['cluster3'],margins=True)

cluster3    0    1    2    3    4   All
DepSeuil                               
False     165  228  154  173  143   863
True       90    9    2    8   69   178
All       255  237  156  181  212  1041